version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: nasa_postgres
    environment:
      POSTGRES_DB: nasa_bi
      POSTGRES_USER: nasa_user
      POSTGRES_PASSWORD: nasa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nasa_user -d nasa_bi"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: webserver
    restart: unless-stopped

  pipeline:
    build: .
    container_name: nasa_etl_pipeline
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - ./data:/app/data
    profiles:
      - manual

volumes:
  postgres_data:
